### ISSUE TITLE
ASP.NET Core From Start to Finish - SalesPage has typo

### ISSUE THREAD

**Issue by AllanRegush** [IAmTimCorey/SiteIssues#1]
While Browsing the site, I noticed that WebAssembly is misspelled under the "what you will learn" section.

![image](https://user-images.githubusercontent.com/17693494/189264846-20192ec1-9c33-4545-b988-ece3a6fb5259.png)

**Comment by TimCorey** [comment]
Fixed! Thanks! And congratulations on being the first issue submitted.
