### ISSUE TITLE
404 Page Showing Stock Azure 404 Page

### ISSUE THREAD

**Issue by ghost** [IAmTimCorey/SiteIssues#10]
The 404 page on [IAmTimCorey.com](https://iamtimcorey.com) displays the stock Azure 404 page, even though this site has a custom 404 page.

I noticed that this site is using Eleventy. I had this same issue on my own Eleventy site and I was able to fix the issue by adding "`permalink: 404.html`" to the Eleventy config at the top of the 404 page. This puts the 404 page at the root as `404.html` instead of at `/404/index.html`.

### Stock Azure 404 Page: https://iamtimcorey.com/asdf

![IAmTimCoreyAzure404](https://github.com/IAmTimCorey/SiteIssues/assets/90208883/e109749f-e9a5-45e3-996e-cc567cdad52d)

### Custom 404 Page: https://iamtimcorey.com/404

![IAmTimCoreyCustom404](https://github.com/IAmTimCorey/SiteIssues/assets/90208883/e20d715a-8cf1-4e3f-ae6d-9ab67f595833)

**Comment by TimCorey** [comment]
Fix completed. Thanks!
