### ISSUE TITLE
Fullscreen breaks slider

### ISSUE THREAD

**Issue by caltman24** [IAmTimCorey/SiteIssues#4]
After going into fullscreen by clicking the actual fullscreen button on the player or clicking "F", attempting to move the playback slider will cause it to immediatley jump to the next lesson.  Hovering over the slider will display "Infinity NaN" instead of the timestamp. However, just double clicking the video to toggle fullscreen will not repoduce this bug.

To Repoduce:
1. Open a lesson and use the toggle fullscreen button on the bottom right of the player or click "F"
2. Attempt to jump to a different timestamp using the slider. 
3. The slider will say "Infinity NaN" and clicking it will jump to the next lesson

**Comment by TimCorey** [comment]
This is, unfortunately, out of our control. It is something controlled by Teachable. We have let them know.
